<?php
session_start();
$line[] = 20;
$line[] = 60;
$line[] = 110;
$line[] = 144;
$line[] = 183;
$line[] = 220;
$line[] = 260;
$line[] = 300;
$v1 = array_rand($line);
$v2 = array_rand($line);
$v3 = array_rand($line);
$v4 = array_rand($line);
$v5 = array_rand($line);
$v6 = array_rand($line);
$hely[] = 30;
$hely[] = 10;
$hely[] = 25;
$hely[] = 5;
$hely[] = 35;
$poz1 = array_rand($hely);
$poz2 = array_rand($hely);
$poz3 = array_rand($hely);
$poz4 = array_rand($hely);
$poz5 = array_rand($hely);
header("Content-type: image/jpeg");
$kep = imagecreatetruecolor(235,85);
$color = imagecolorallocate($kep, 150, 150, 150);
$vonal = imagecolorallocate($kep, 106, 196, 78);
$vonal2 = imagecolorallocate($kep, 66, 169, 153);
imagefill($kep, 0, 0, $color);
if (isset($_SESSION['captcha'])) $szoveg=$_SESSION['captcha'];
else $szoveg='error';
$kep2 =  imagecreatefromjpeg("captcha/".$szoveg[0] . ".jpeg");
$kep3 =  imagecreatefromjpeg("captcha/".$szoveg[1] . ".jpeg");
$kep4 =  imagecreatefromjpeg("captcha/".$szoveg[2] . ".jpeg");
$kep5 =  imagecreatefromjpeg("captcha/".$szoveg[3] . ".jpeg");
$kep6 =  imagecreatefromjpeg("captcha/".$szoveg[4] . ".jpeg");
imagecopy($kep, $kep2, 20, $hely[$poz1], 0, 0, 40, 40);
imagecopy($kep, $kep3, 60, $hely[$poz2], 0, 0, 40, 40);
imagecopy($kep, $kep4, 100, $hely[$poz3], 0, 0, 40, 40);
imagecopy($kep, $kep5, 140, $hely[$poz4], 0, 0, 40, 40);
imagecopy($kep, $kep6, 180, $hely[$poz5], 0, 0, 40, 40);
imageline($kep, $line[$v1], 20, 0, 0, $vonal);
imageline($kep, $line[$v2], 170, 0, 50, $vonal2);
imageline($kep, $line[$v3], 70, 0, 100, $vonal);
imageline($kep, $line[$v4], 50, 0, 50, $vonal2);
imageline($kep, $line[$v5], 170, 0, 100, $vonal);
imageline($kep, $line[$v6], 70, 0, 0, $vonal2);
imagejpeg($kep);
?>